# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cf1f8bf84d60e93f8ad57f303f759761e8ceb40be5932b634dbc2029d989f53524ea3de475bea9e8592e16419417a4c4337ee67e4d65684fa827eafe635be41

test:
  secret_key_base: b7a17ad8a7eb38ebcb225d07367166b0855672ac4bc570e3f0b7d0366735e054e45db8da3a11de5bc584b36bce242b4357c88c6a479cd766ad53c3baef120d11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
